// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Termini_Api.TerminiDbContext;

#nullable disable

namespace Termini_Api.Migrations
{
    [DbContext(typeof(TerminiDBContext))]
    [Migration("20260411142626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Termini_Api.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Termini_Api.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SportId"));

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SportId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Termini_Api.Models.Teren", b =>
                {
                    b.Property<long>("TerenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TerenId"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<long>("ClientUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OpenFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OpenTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<string>("TerenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TerenId");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("SportId");

                    b.ToTable("Terens");
                });

            modelBuilder.Entity("Termini_Api.Models.Termin", b =>
                {
                    b.Property<long>("TerminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TerminId"));

                    b.Property<long>("BeneficiaryUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("TerenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TerminDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TerminOd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TerminId");

                    b.HasIndex("BeneficiaryUserId");

                    b.HasIndex("TerenId");

                    b.ToTable("Termins");
                });

            modelBuilder.Entity("Termini_Api.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Termini_Api.Models.Beneficiary", b =>
                {
                    b.HasBaseType("Termini_Api.Models.User");

                    b.Property<long>("BeneficiaryId")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Beneficiary");
                });

            modelBuilder.Entity("Termini_Api.Models.Client", b =>
                {
                    b.HasBaseType("Termini_Api.Models.User");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Termini_Api.Models.Teren", b =>
                {
                    b.HasOne("Termini_Api.Models.City", "City")
                        .WithMany("Tereni")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termini_Api.Models.Client", "Client")
                        .WithMany("Tereni")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termini_Api.Models.Sport", "Sport")
                        .WithMany("Tereni")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Client");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Termini_Api.Models.Termin", b =>
                {
                    b.HasOne("Termini_Api.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Termini_Api.Models.Teren", "Teren")
                        .WithMany("Termins")
                        .HasForeignKey("TerenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Teren");
                });

            modelBuilder.Entity("Termini_Api.Models.City", b =>
                {
                    b.Navigation("Tereni");
                });

            modelBuilder.Entity("Termini_Api.Models.Sport", b =>
                {
                    b.Navigation("Tereni");
                });

            modelBuilder.Entity("Termini_Api.Models.Teren", b =>
                {
                    b.Navigation("Termins");
                });

            modelBuilder.Entity("Termini_Api.Models.Client", b =>
                {
                    b.Navigation("Tereni");
                });
#pragma warning restore 612, 618
        }
    }
}
